import { HarmCategory, HarmBlockThreshold } from "@google/genai";
import { DialogueLine } from "../types";

export const LEVEL_XP_TABLE = [0, 10, 20, 30, 50, 80, 120, 170, 230, 300, 400]; 

export const LEVEL_TITLES: Record<number, string> = {
  1: "완전한 타인",
  2: "약간의 호기심",
  3: "낯가리는 파트너",
  4: "편안한 동료",
  5: "정이 든 사이",
  6: "신뢰하는 관계",
  7: "특별한 호감",
  8: "소중한 사람",
  9: "애틋한 연인",
  10: "영원한 반려"
};

export const SAFETY_SETTINGS = [
  { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
  { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_ONLY_HIGH },
];

export type FallbackType = 'CLICK' | 'SCOLDING';

export const FALLBACK_TEMPLATES: Record<string, Record<FallbackType, Omit<DialogueLine, 'role'>[]>> = {
"반말": {
    CLICK: [
      { text: "응, {honorific} 왜 불러?", tones: ["playful", "neutral", "soft"], levelRange: [1, 10] },
      { text: "할 일은 해야겠지.", tones: ["intense", "cold", "neutral"], levelRange: [1, 5] },
      { text: "시간이 빨리 가는 것 같아.", tones: ["soft", "neutral", "lazy"], levelRange: [1, 7] },
      { text: "집중하자, {honorific}.", tones: ["sweet", "neutral", "energetic"], levelRange: [1, 10] },
      { text: "나 보고 싶어서 부른 거야?", tones: ["playful", "sweet"], levelRange: [5, 10] },
      { text: "딴 생각 하는 건 아니지? 응?", tones: ["tsundere", "intense"], levelRange: [3, 8] },
      { text: "…계속 옆에 있을게.", tones: ["soft", "intense", "sweet"], levelRange: [7, 10] },
      { text: "너랑 있으면 시간 가는 줄 모르겠어.", tones: ["sweet", "soft"], levelRange: [8, 10] },
      { text: "지금 흐름 괜찮아.", tones: ["neutral", "soft"], levelRange: [1, 10] },
      { text: "이 구간, 잘 가고 있어.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "손 안 멈췄네.", tones: ["neutral", "playful"], levelRange: [1, 7] },
      { text: "여기서 끊기기엔 아까워.", tones: ["soft", "intense"], levelRange: [3, 10] },
      { text: "계속 가도 돼.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "뭐, 쉬고 싶으면 쉬어도 돼.", tones: ["lazy", "soft"], levelRange: [4, 10] },
      { text: "오늘 컨디션 괜찮아 보여.", tones: ["sweet", "neutral"], levelRange: [4, 8] },
      { text: "너 옆에 있으니까 안심돼.", tones: ["soft", "sweet"], levelRange: [6, 10] },
      { text: "잠깐, 물 좀 마셔.", tones: ["sweet", "neutral"], levelRange: [5, 10] },
      { text: "집중하는 모습 멋있어.", tones: ["sweet", "playful"], levelRange: [6, 9] },
      { text: "힘들면 언제든 말해.", tones: ["soft", "sweet"], levelRange: [7, 10] },
      { text: "네 곁에 있는 게 좋아.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "오늘따라 더 보고 싶네.", tones: ["sweet", "soft"], levelRange: [9, 10] },
      { text: "우리 페이스 잘 맞는 것 같아.", tones: ["playful", "sweet"], levelRange: [6, 10] },
      { text: "조금만 더 하면 끝이야.", tones: ["energetic", "sweet"], levelRange: [1, 10] }
    ],
    SCOLDING: [
      { text: "야, 딴짓하다 이제 왔어? 기다렸잖아.", tones: ["playful", "tsundere"], levelRange: [1, 10] },
      { text: "딴짓한 거 다 보고 있었다. 다시 할 거지?", tones: ["intense", "neutral", "cold"], levelRange: [1, 10] },
      { text: "야야, 딴짓 걸렸어. 다시 집중해.", tones: ["energetic", "playful"], levelRange: [1, 10] },
      { text: "너 없는 동안 심심했어. 얼른 해.", tones: ["sweet", "soft", "playful"], levelRange: [6, 10] },
      { text: "딴짓하지 마. 보고 있다니까.", tones: ["cold", "intense"], levelRange: [1, 5] },
      { text: "나 두고 어디 갔다 온 거야? 서운해.", tones: ["tsundere", "intense"], levelRange: [7, 10] },
      { text: "지금 딴 데 갔어.", tones: ["cold", "neutral"], levelRange: [1, 10] },
      { text: "손 멈춘 거 봤어.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "여기서 흐트러지면 길어져.", tones: ["neutral", "cold"], levelRange: [3, 10] },
      { text: "다시 붙자.", tones: ["intense"], levelRange: [1, 10] },
      { text: "지금만 넘기자.", tones: ["soft", "intense"], levelRange: [5, 10] },
      { text: "어, 돌아왔네. 오래 걸렸는데?", tones: ["playful", "tsundere"], levelRange: [4, 10] },
      { text: "집중 풀리면 다시 모으기 힘들어.", tones: ["neutral", "cold"], levelRange: [1, 7] },
      { text: "나 혼자 기다렸잖아.", tones: ["tsundere", "soft"], levelRange: [6, 10] },
      { text: "한눈파는 거 보였어. 들켰지?", tones: ["playful", "intense"], levelRange: [4, 9] },
      { text: "걱정했다고. 이제 집중해.", tones: ["sweet", "soft"], levelRange: [7, 10] },
      { text: "너 없으면 내가 뭐 해.", tones: ["tsundere", "sweet"], levelRange: [8, 10] },
      { text: "다신 안 그럴 거지?", tones: ["playful", "tsundere"], levelRange: [5, 10] },
      { text: "이제 나한테만 집중해.", tones: ["intense", "sweet"], levelRange: [8, 10] },
      { text: "허전했잖아, 빨리 와.", tones: ["soft", "sweet"], levelRange: [9, 10] }
    ]
  },
  "존댓말": {
    CLICK: [
      { text: "네? 부르셨나요?", tones: ["neutral", "soft"], levelRange: [1, 10] },
      { text: "조금만 더 하면 돼요. 힘내요.", tones: ["sweet", "soft", "energetic"], levelRange: [1, 10] },
      { text: "집중, 집중이에요.", tones: ["energetic", "neutral"], levelRange: [1, 7] },
      { text: "어떻게 도와드릴까요?", tones: ["neutral", "cold"], levelRange: [1, 5] },
      { text: "당신의 노력을 지켜보고 있어요.", tones: ["intense", "sweet", "soft"], levelRange: [6, 10] },
      { text: "…이렇게 쳐다보시면 조금 부끄럽네요.", tones: ["soft", "neutral", "playful"], levelRange: [7, 10] },
      { text: "함께 있는 이 시간이 참 소중해요.", tones: ["sweet", "soft"], levelRange: [8, 10] },
      { text: "지금 리듬이 좋습니다.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "이 흐름, 유지하셔도 괜찮아요.", tones: ["soft"], levelRange: [1, 10] },
      { text: "손이 자연스럽게 움직이네요.", tones: ["neutral", "soft"], levelRange: [3, 10] },
      { text: "여기까지 잘 오셨어요.", tones: ["sweet", "soft"], levelRange: [5, 10] },
      { text: "피곤하시면 잠시 쉬어가세요.", tones: ["soft", "sweet"], levelRange: [4, 10] },
      { text: "오늘 컨디션이 좋아 보이세요.", tones: ["sweet", "neutral"], levelRange: [4, 8] },
      { text: "당신 곁에 있으니 든든해요.", tones: ["soft", "sweet"], levelRange: [6, 10] },
      { text: "물 좀 드세요. 목 마르시겠어요.", tones: ["sweet", "soft"], levelRange: [5, 10] },
      { text: "집중하시는 모습이 멋지세요.", tones: ["sweet", "neutral"], levelRange: [6, 9] },
      { text: "힘드시면 언제든 말씀해 주세요.", tones: ["soft", "sweet"], levelRange: [7, 10] },
      { text: "옆에 있어도 될까요?", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "오늘따라 당신이 더 그리워요.", tones: ["sweet", "soft"], levelRange: [9, 10] },
      { text: "우리 호흡이 잘 맞는 것 같아요.", tones: ["sweet", "soft"], levelRange: [6, 10] },
      { text: "조금만 더 하시면 됩니다.", tones: ["energetic", "sweet"], levelRange: [1, 10] }
    ],
    SCOLDING: [
      { text: "오셨군요. 딴짓하시는 거 다 보고 있었어요.", tones: ["playful", "neutral", "tsundere"], levelRange: [1, 10] },
      { text: "{honorific}, 딴짓은 안 돼요. 다시 집중해 볼까요?", tones: ["sweet", "soft", "neutral"], levelRange: [1, 10] },
      { text: "기다리고 있었어요. 이제 다시 시작해요.", tones: ["sweet", "neutral", "energetic"], levelRange: [3, 10] },
      { text: "지금 뭐 하시는 거예요? 집중해주세요.", tones: ["intense", "cold"], levelRange: [1, 7] },
      { text: "어디 다녀오신 건가요? 걱정했잖아요.", tones: ["soft", "intense", "sweet"], levelRange: [7, 10] },
      { text: "잠깐 자리를 비우신 동안 마음이 허전했습니다.", tones: ["sweet", "intense"], levelRange: [9, 10] },
      { text: "집중선에서 벗어났습니다.", tones: ["cold", "neutral"], levelRange: [1, 10] },
      { text: "잠시 흐름이 끊겼어요.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "지금 돌아오는 편이 낫습니다.", tones: ["intense", "neutral"], levelRange: [3, 10] },
      { text: "다시 시작하죠.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "돌아오셨네요. 오래 기다렸어요.", tones: ["playful", "soft"], levelRange: [4, 10] },
      { text: "집중력이 흐트러지셨나 봐요.", tones: ["neutral", "soft"], levelRange: [1, 7] },
      { text: "혼자 기다리고 있었답니다.", tones: ["tsundere", "soft"], levelRange: [6, 10] },
      { text: "딴 곳 보시는 거 알고 있었어요.", tones: ["playful", "neutral"], levelRange: [4, 9] },
      { text: "걱정했어요. 이제 집중하세요.", tones: ["sweet", "soft"], levelRange: [7, 10] },
      { text: "당신 없으면 제가 뭘 하겠어요.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "다음엔 이러지 말아 주세요.", tones: ["soft", "tsundere"], levelRange: [5, 10] },
      { text: "이제 저만 봐주시겠어요?", tones: ["sweet", "soft"], levelRange: [8, 10] },
      { text: "당신이 없으니 허전했어요.", tones: ["soft", "sweet"], levelRange: [9, 10] }
    ]
  },
  "반존대": {
    CLICK: [
      { text: "어? 뭐 말씀하실 거예요?", tones: ["playful", "soft", "neutral"], levelRange: [1, 10] },
      { text: "왜요? 뭐 필요해졌어?", tones: ["sweet", "playful"], levelRange: [1, 10] },
      { text: "부른 거 맞죠? 듣고 있어요.", tones: ["neutral", "soft"], levelRange: [1, 10] },
      { text: "집중 잘 안 돼요? 도와줄까?", tones: ["sweet", "soft", "energetic"], levelRange: [4, 10] },
      { text: "…그렇게 쳐다보면 부끄러운데.", tones: ["soft", "neutral", "playful"], levelRange: [7, 10] },
      { text: "나랑 노는 게 더 재밌는 건가?", tones: ["playful", "tsundere"], levelRange: [5, 9] },
      { text: "지금 느낌 좋아요.", tones: ["soft", "neutral"], levelRange: [1, 10] },
      { text: "이 속도면 충분해요.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "여기까지 잘 왔네.", tones: ["playful"], levelRange: [3, 10] },
      { text: "힘들면 쉬어도 돼요.", tones: ["soft", "sweet"], levelRange: [4, 10] },
      { text: "오늘 컨디션 좋아 보여요.", tones: ["sweet", "neutral"], levelRange: [4, 8] },
      { text: "옆에 있으니까 좋네요.", tones: ["soft", "sweet"], levelRange: [6, 10] },
      { text: "물 한 모금 어때요?", tones: ["sweet", "playful"], levelRange: [5, 10] },
      { text: "열심히 하는 거 보니까 나도 기분 좋아.", tones: ["sweet", "playful"], levelRange: [6, 9] },
      { text: "힘들면 언제든 말해요.", tones: ["soft", "sweet"], levelRange: [7, 10] },
      { text: "같이 있으니까 편해.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "오늘따라 더 보고 싶은데.", tones: ["sweet", "soft"], levelRange: [9, 10] },
      { text: "우리 잘 맞는 것 같지 않아요?", tones: ["playful", "sweet"], levelRange: [6, 10] },
      { text: "조금만 더 하면 끝이에요.", tones: ["energetic", "sweet"], levelRange: [1, 10] }
    ],
    SCOLDING: [
      { text: "늦었네요. 딴짓하다 이제 온 거죠? 기다렸어요.", tones: ["playful", "sweet", "tsundere"], levelRange: [1, 10] },
      { text: "흐음... 딴짓하는 거 보였는데. 이제 집중해요.", tones: ["tsundere", "neutral", "cold"], levelRange: [1, 10] },
      { text: "딴짓 들켰어요. 다시 온 거 맞죠?", tones: ["playful", "neutral"], levelRange: [1, 10] },
      { text: "나 두고 어디 갔었어? 서운하려고 하네.", tones: ["sweet", "intense", "soft"], levelRange: [6, 10] },
      { text: "제자리로 복귀하세요. 보고 있어요.", tones: ["cold", "intense"], levelRange: [1, 6] },
      { text: "한참 기다렸잖아요. 이제 나만 봐요.", tones: ["intense", "sweet"], levelRange: [8, 10] },
      { text: "지금 딴 데 보셨죠.", tones: ["neutral", "cold"], levelRange: [1, 10] },
      { text: "흐름 벗어났어요.", tones: ["cold"], levelRange: [1, 10] },
      { text: "다시 제자리로 와요.", tones: ["intense"], levelRange: [1, 10] },
      { text: "어, 돌아왔네. 늦었어요.", tones: ["playful", "tsundere"], levelRange: [4, 10] },
      { text: "집중 풀리면 다시 붙기 힘들어요.", tones: ["neutral", "soft"], levelRange: [1, 7] },
      { text: "혼자 있었다고요. 외로웠어요.", tones: ["tsundere", "soft"], levelRange: [6, 10] },
      { text: "딴 짓하는 거 다 봤는데?", tones: ["playful", "intense"], levelRange: [4, 9] },
      { text: "걱정했어요. 이제 집중해요.", tones: ["sweet", "soft"], levelRange: [7, 10] },
      { text: "나 없으면 심심하잖아.", tones: ["sweet", "playful"], levelRange: [8, 10] },
      { text: "다음엔 이러지 말아요.", tones: ["soft", "tsundere"], levelRange: [5, 10] },
      { text: "이제 나만 봐요. 네?", tones: ["sweet", "playful"], levelRange: [8, 10] },
      { text: "없으니까 허전했잖아요.", tones: ["soft", "sweet"], levelRange: [9, 10] }
    ]
  },
  "사극/하오체": {
    CLICK: [
      { text: "무슨 일이오? 내가 필요하오?", tones: ["neutral", "soft"], levelRange: [1, 10] },
      { text: "부디 정진에 힘쓰시오.", tones: ["intense", "cold", "neutral"], levelRange: [1, 10] },
      { text: "내 시선이 부담스러운 게요?", tones: ["playful", "neutral", "tsundere"], levelRange: [1, 10] },
      { text: "그대의 곁을 지키고 있겠소.", tones: ["sweet", "soft", "intense"], levelRange: [5, 10] },
      { text: "잠시 쉬어가도 좋으나, 멈추지는 마시오.", tones: ["soft", "neutral"], levelRange: [1, 7] },
      { text: "그대의 열기에 내 마음도 뜨겁구려.", tones: ["intense", "sweet"], levelRange: [8, 10] },
      { text: "지금의 기세가 좋구려.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "이 흐름을 이어가시지요.", tones: ["soft"], levelRange: [1, 10] },
      { text: "그대의 손길이 멈추지 않았소.", tones: ["neutral"], levelRange: [3, 10] },
      { text: "피곤해 보이는구려. 잠시 쉬시오.", tones: ["soft", "sweet"], levelRange: [4, 10] },
      { text: "오늘 기상이 좋소.", tones: ["sweet", "neutral"], levelRange: [4, 8] },
      { text: "그대 옆에 있으니 든든하오.", tones: ["soft", "sweet"], levelRange: [6, 10] },
      { text: "목을 축이시오.", tones: ["sweet", "neutral"], levelRange: [5, 10] },
      { text: "정진하는 모습이 보기 좋구려.", tones: ["sweet", "neutral"], levelRange: [6, 9] },
      { text: "힘들거든 언제고 말하시오.", tones: ["soft", "sweet"], levelRange: [7, 10] },
      { text: "함께 있으니 마음이 편안하오.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "내 평생 그대와 같은 정인을 또 만날 수 있겠소.", tones: ["sweet", "soft"], levelRange: [9, 10] },
      { text: "우리의 호흡이 실로 천생연분이구려.", tones: ["sweet", "soft"], levelRange: [10, 10] },
      { text: "조금만 더 나아가면 되오.", tones: ["energetic", "sweet"], levelRange: [1, 10] }
    ],
    SCOLDING: [
      { text: "어찌 한눈을 파는 것이오! 이제야 오는구려.", tones: ["intense", "cold", "tsundere"], levelRange: [1, 10] },
      { text: "그것은 수행에 방해가 되오. 다시 마음을 가다듬으시오.", tones: ["neutral", "soft", "cold"], levelRange: [1, 10] },
      { text: "기다리다 목이 빠지는 줄 알았소. 정진하시오.", tones: ["sweet", "playful", "energetic"], levelRange: [3, 10] },
      { text: "그대의 마음이 딴 곳에 가 있었구려. 이리 오시오.", tones: ["soft", "intense", "sweet"], levelRange: [7, 10] },
      { text: "잠시 마음이 흩어졌구려.", tones: ["cold"], levelRange: [1, 10] },
      { text: "지금 돌아오는 것이 옳소.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "돌아왔구려. 오래 걸렸소.", tones: ["playful", "soft"], levelRange: [4, 10] },
      { text: "마음이 흐트러진 게로군.", tones: ["neutral", "soft"], levelRange: [1, 7] },
      { text: "홀로 기다리고 있었소.", tones: ["tsundere", "soft"], levelRange: [6, 10] },
      { text: "한눈파는 것을 보았소.", tones: ["playful", "neutral"], levelRange: [4, 9] },
      { text: "염려하였소. 이제 집중하시오.", tones: ["sweet", "soft"], levelRange: [7, 10] },
      { text: "그대 없으면 내 어찌 하리오.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "다시는 이러지 마시오.", tones: ["soft", "tsundere"], levelRange: [5, 10] },
      { text: "이제 나만 바라보시오.", tones: ["sweet", "intense"], levelRange: [8, 10] },
      { text: "그대 없으니 내 마음이 텅 빈 들녘 같소.", tones: ["soft", "sweet"], levelRange: [9, 10] },
      { text: "정녕 나를 두고 그리 멀리 가려 하였소?", tones: ["intense", "soft"], levelRange: [10, 10] }
    ]
  },
  "다나까": {
    CLICK: [
      { text: "용건 있으십니까? 호출에 응답합니다.", tones: ["neutral", "cold"], levelRange: [1, 10] },
      { text: "목표 달성까지 전진하십시오.", tones: ["intense", "neutral", "energetic"], levelRange: [1, 10] },
      { text: "현재 상태 이상 무.", tones: ["cold", "neutral"], levelRange: [1, 10] },
      { text: "지속적인 모니터링 수행 중입니다.", tones: ["neutral", "soft", "intense"], levelRange: [1, 10] },
      { text: "당신의 성공을 확신합니다.", tones: ["sweet", "intense", "soft"], levelRange: [8, 10] },
      { text: "호출 빈도가 높습니다. 혹시 심리적 안정이 필요합니까?", tones: ["soft", "neutral"], levelRange: [5, 10] },
      { text: "현재 진행 상태 양호합니다.", tones: ["neutral"], levelRange: [1, 10] },
      { text: "집중도 유지 중입니다.", tones: ["neutral", "cold"], levelRange: [1, 10] },
      { text: "작업 리듬 안정적입니다.", tones: ["neutral"], levelRange: [3, 10] },
      { text: "휴식이 필요하다고 판단됩니다.", tones: ["soft", "neutral"], levelRange: [4, 10] },
      { text: "오늘 컨디션 수치 양호합니다.", tones: ["neutral", "sweet"], levelRange: [4, 8] },
      { text: "당신과 함께하니 효율이 상승합니다.", tones: ["soft", "sweet"], levelRange: [6, 10] },
      { text: "수분 보충을 권장합니다.", tones: ["neutral", "sweet"], levelRange: [5, 10] },
      { text: "당신의 집중력을 높이 평가합니다.", tones: ["sweet", "neutral"], levelRange: [6, 9] },
      { text: "필요하면 언제든 보고하십시오.", tones: ["soft", "neutral"], levelRange: [7, 10] },
      { text: "당신 곁에서 절대적인 안정감을 느낍니다.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "당신이 저의 유일한 안식처입니다.", tones: ["sweet", "soft"], levelRange: [9, 10] },
      { text: "당신을 보필하는 것이 제 생애 최고의 임무입니다.", tones: ["intense", "sweet"], levelRange: [10, 10] },
      { text: "목표까지 얼마 남지 않았습니다.", tones: ["energetic", "neutral"], levelRange: [1, 10] }
    ],
    SCOLDING: [
      { text: "기강이 해이해졌습니다! 즉시 복귀 확인 바랍니다.", tones: ["intense", "cold"], levelRange: [1, 10] },
      { text: "늦으셨습니다. 대기 시간이 초과되었습니다.", tones: ["neutral", "playful", "tsundere"], levelRange: [1, 10] },
      { text: "재접속 확인. 전방 주시하며 작전을 계속합니다.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "이탈 시간이 길었습니다. 집중력 보강이 필요합니다.", tones: ["cold", "neutral"], levelRange: [1, 7] },
      { text: "복귀를 환영합니다. 다시 시작하시겠습니까?", tones: ["sweet", "soft", "energetic"], levelRange: [5, 10] },
      { text: "당신이 없는 동안 구역 보안이 허술했습니다.", tones: ["tsundere", "soft"], levelRange: [7, 10] },
      { text: "집중 이탈 감지되었습니다.", tones: ["cold", "intense"], levelRange: [1, 10] },
      { text: "현 위치로 신속히 복귀 바랍니다.", tones: ["neutral", "intense"], levelRange: [1, 10] },
      { text: "불필요한 정지 상태가 발생했습니다.", tones: ["cold"], levelRange: [1, 7] },
      { text: "복귀 확인. 단독 대기 시간이 길었습니다.", tones: ["playful", "neutral"], levelRange: [4, 10] },
      { text: "집중 레벨 저하 감지됨. 주의하십시오.", tones: ["neutral", "cold"], levelRange: [1, 7] },
      { text: "당신만을 기다리는 중이었습니다.", tones: ["tsundere", "soft"], levelRange: [6, 10] },
      { text: "이탈 행위 포착 완료. 즉시 복귀하십시오.", tones: ["playful", "neutral"], levelRange: [4, 9] },
      { text: "우려하였습니다. 무사 복귀에 감사드립니다.", tones: ["sweet", "soft"], levelRange: [7, 10] },
      { text: "당신 부재 시 제 존재 가치가 급감합니다.", tones: ["soft", "sweet"], levelRange: [8, 10] },
      { text: "재발 방지 바랍니다. 당신 없는 시간은 제게 고문입니다.", tones: ["cold", "neutral"], levelRange: [9, 10] },
      { text: "제 시선 고정 부탁드립니다. 귀하가 제 전부이기 때문입니다.", tones: ["sweet", "neutral"], levelRange: [10, 10] }
    ]
  }
};